name: Generate Atom news feeds

on:
  repository_dispatch:
    types:
      - resource-published
  schedule:
    - cron: '30 0 * * *'
  pull_request:
    paths:
      - '.github/ci/**'
      - '.github/workflows/generate-atom-news-feeds.yaml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v5
        # Do not set ref: github.head_ref.
        # checkout selects the correct event ref automatically.
        with:
          token: ${{ secrets.BOT_ACCESS_TOKEN || github.token }}

      - name: Configure git
        run: |
          git config user.name "GitHubActions"
          git config user.email "actions@github.com"

      - uses: actions/setup-node@v5
        with:
          node-version: '24'

      - name: Install dependencies
        working-directory: ./.github/ci
        run: npm install

      - name: Generate Feed
        working-directory: ./.github/ci
        run: node generate-news-feed.js

      - name: Commit and push changes
        if: github.event_name != 'pull_request'
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "Update feed.xml"